version: "3.8"

services:
  app:
    image: chatapp
    environment:
      MONGO_URL: "mongodb://db:27017/test"
    depends_on:
      - db
    ports:
      - "8080:8080"

  db:
    image: mongo