version: "3.8"

services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - /data/db:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    restart: always 
  app:
    build: .
    container_name: app
    environment:
      PORT: 8080
      JWT_KEY: "asjh564sdf5wefsdf4sf"
      DB_CNN: mongo://localhost:27017/test
      DD_USER: root
      DD_PASS: root
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    restart: always
    depends_on:
      - db
  