name: chat-backend

on: 
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  ci_to_master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - env:
          DB_CNN: ${{ secrets.DB_CNN }}
          JWT_KEY: ${{ secrets.JWT_KEY }}
      - run: npm ci
      - run: npm test
      - run: npm run start